import type { Community } from "./types";
import { pickExampleModelHomeImage } from "./model-home-images";

const YOUTUBE_URL = "https://www.youtube.com/watch?v=rObOyU4SXuw";
const THUMBNAIL_URL =
  "https://img.youtube.com/vi/rObOyU4SXuw/hqdefault.jpg";

export const seedCommunities: Community[] = [
  {
    id: "seed-waxhaw",
    name: "Village of Waxhaw",
    city: "Waxhaw",
    description:
      "New community of spacious townhomes with two-car garages in Waxhaw, NC. Residents are within easy walking distance of downtown Waxhaw for local shops, retail, and grocery stores, with a short drive to Uptown Charlotte and the Promenade at Carolina Reserve shopping center. Zoned for Union County Public Schools.",
    thumbnailUrl: THUMBNAIL_URL,
    youtubeUrl: YOUTUBE_URL,
    builderName: "Lennar",
    builderId: "seed-builder-lennar",
    builderIds: ["seed-builder-lennar"],
    isMultiBuilder: false,
    tags: ["new-construction", "townhomes"],
    builderOffers: "",
    realtorName: "Previax Team",
    realtorPhone: "",
    realtorEmail: "inquiries@previax.com",
    realtorPhotoUrl: "/previax-logo.png",
    amenities: [
      "Two-car garages",
      "Walking distance to downtown Waxhaw",
      "Close to Uptown Charlotte",
    ],
    lenders: ["Lennar Mortgage"],
    mainHighlight: "Walkable to downtown Waxhaw",
    schoolDistrict: "",
    commuteNotes: "",
    hoaRange: "",
    offerExpires: "",
    tagline: "",
    lifestyleNotes: "",
    schoolOverview: "",
    schools: [],
    diningOverview: "",
    nearbyPlaces: [],
    reviews: [],
    mediaGallery: [],
    createdAt: Date.now() - 86400000,
    homes: [
      {
        id: "seed-waxhaw-home-copeland",
        seriesId: "seed-series-waxhaw",
        modelName: "Copeland",
        address: "",
        tags: ["move-in-ready"],
        listingCategories: [],
        price: 0,
        bedrooms: 0,
        bathrooms: 0,
        sqft: 0,
        imageUrls: [pickExampleModelHomeImage("Village of Waxhaw:Copeland")],
        description:
          "Three-story townhome with a lower-level game room and two-car garage. The main level opens up to a sprawling family room, dining room, and chef-ready kitchen with a deck. The top floor holds two secondary bedrooms and the owner's suite. 3 bed / 3.5 bath, approx. 2,408-2,512 sq ft.",
        tagline: "",
        featuresOverview: "",
        highlights: [],
        rooms: [],
        reviews: [],
        mediaGallery: [],
        status: "available",
      },
      {
        id: "seed-waxhaw-home-beswick",
        seriesId: "seed-series-waxhaw",
        modelName: "Beswick",
        address: "",
        tags: ["move-in-ready"],
        listingCategories: [],
        price: 0,
        bedrooms: 0,
        bathrooms: 0,
        sqft: 0,
        imageUrls: [pickExampleModelHomeImage("Village of Waxhaw:Beswick")],
        description:
          "Three-story townhome with a lower-level game room and two-car garage. Upstairs offers an open floorplan connecting the family room, kitchen, and breakfast room with deck access. All three bedrooms, including the owner's suite, sit on the top floor. 3-4 bed / 3.5 bath, approx. 2,423-2,431 sq ft.",
        tagline: "",
        featuresOverview: "",
        highlights: [],
        rooms: [],
        reviews: [],
        mediaGallery: [],
        status: "available",
      },
      {
        id: "seed-waxhaw-home-aynsley",
        seriesId: "seed-series-waxhaw",
        modelName: "Aynsley",
        address: "",
        tags: ["move-in-ready"],
        listingCategories: [],
        price: 0,
        bedrooms: 0,
        bathrooms: 0,
        sqft: 0,
        imageUrls: [pickExampleModelHomeImage("Village of Waxhaw:Aynsley")],
        description:
          "Three-story townhome with a lower-level bonus room and two-car garage. Upstairs, an open-plan layout connects the kitchen, breakfast room, and family room with a deck. All three bedrooms, including the owner's suite, are on the top floor. 3 bed / 3.5 bath, approx. 2,408-2,511 sq ft.",
        tagline: "",
        featuresOverview: "",
        highlights: [],
        rooms: [],
        reviews: [],
        mediaGallery: [],
        status: "available",
      },
    ],
  },
];
